name: Linux Container Node Workflow

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: springsh.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build ./student-service/ -t springsh.azurecr.io/springsh:${{ github.sha }}
        docker push springsh.azurecr.io/springsh:${{ github.sha }}  