name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build -t registry.hub.docker.com/dl3c01n/spring-sh ./student-service/
        docker push registry.hub.docker.com/dl3c01n/spring-sh
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'springsh'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'registry.hub.docker.com/dl3c01n/spring-sh'